### ISSUE TITLE
The reddit.com add-on player

### ISSUE THREAD

**Issue by ghost** [metate/official-meta-players#2]
http://pastebin.com/GANBfpnX

**Comment by metate** [comment]
It needs some improvements to be useful. I'll look into it later. Thanks!

**Comment by ghost** [comment]
I've made some small adjustments to it. for TV shows it'll now first search for stuff about the episode, if it can't find anything it will search for stuff about the season, and if it still can't find anything it'll search for stuff about the show itself.

https://gist.github.com/midraal/bb5a0eef2249742938a2

**Comment by metate** [comment]
Added. Thanks!
