### ISSUE TITLE
ABC Family, Syfy, Crackler Add-on players

### ISSUE THREAD

**Issue by ghost** [metate/official-meta-players#4]
ABC Family: http://pastebin.com/NgQVFXmw

Syfy: http://pastebin.com/Cve414aQ

Crackler: http://pastebin.com/e5xwdisr

**Comment by metate** [comment]
All added! thanks!

**Comment by metate** [comment]
I changed Crackler again to match by season and episode first, and fallback to title if needed. Seems to work here but if you encounter any problem please let me know.
